### ISSUE TITLE
Hallway radio

### ISSUE THREAD

**Issue by thenfour** [thenfour/digifujam#230]
host a streaming radio station in the hallway. probably the idea is to run an icecast server and expose it in the #hallway room.

* enable control via slash commands. see bots like https://fredboat.com/ for how users are doing this
* should ensure ios compatibility; would be a real shame to build a radio that doesn't work on iphones.

Feature breakdown:

* Icecast server running at uberspace (trivial) https://lab.uberspace.de/guide_icecast2.html
* 7jam room integrations with the icecast server
  * Player:
    * ability to play (trivial: <audio> or createMediaStreamSourceNode)
    * visualization
    * metadata parsing & displaying
  * Stream source.
    * We must always support the native icecast stream source, to support DJing from foobar with commentary whatever.
    * But I think it's going to be very useful to have a built-in 7jam media player; it would solidify the integration a bit. but not trivial:
      * need ability to in-browser convert media to .ogg
      * and i don't think it's trivial at all to do this from the 7jam node server; would be best done in some native separate application i believe. or separate node application. Uberspace explicitly discourages (soft ban) transcoders like this, probably for exactly this reason.
      * consider https://icecast.org/ezstream/ ? or other command line sources like https://icecast.org/apps/. MPD is a daemon which could theoretically be a source but i think it's a bit heavy-handed for what we need.
      * can be done with ffmpeg (`ffmpeg -i "song.mp3" -f mp3 icecast://source:password@host:8000/maj7`).
      * another streaming source daemon, but i think very inflexible: https://icecast.org/ices/
  * so most of the time, 7jam is a stream source, but can be delegated. Actually it would be very much like existing 7jam instrument control. One person controls at a time, with idle timeout.
  * Q: how do users get a token to stream? for the moment i think it's going to be a manual process.
* Discord voice relay
  * to bring the audio direct to discord
  * to announce stream things like metadata and events
  * feels like this is also trivial: things like this exist with few lines of code https://github.com/leinstay/discobot
* Artwork for the hallway would be cool, tailored to the function of a listening room. Probably should rename the room as well, or create a separate room?

----------

# Roadmap

- [x] Configure an icecast2 server with SSH and ports open for streaming. Done: https://radio.7jam.io/
- [x] POC of discord voice relay, probe for design decisions.
- [x] Player: Create a basic player in #hallway with a POC visualizer
- [x] Player: Display stream metadata somewhere
- [ ] Radio stream source
- Cancelled: Discord voice relay. To make the radio more available, relay it to a HQ discord voice channel. Cancelling this idea because 1) it's a very inefficient process, 2) would require more infrastructure than i want, 3) Discord voice chans are not excellent for this, 4) would decentralize the radio, 5) better use this energy to improve the 7jam experience

-------------

# POC relay stream to discord

So this works but I don't like the fact that it's ... just kinda unnecessarily coupled to 7jam. Pretty sure it could just as easily run in completely separate instance. basically a totally separate bot which just handles relaying a stream. Don't pollute 7jam's node server with this.

```
            const g = this.client.guilds.cache.get('...');
            const v = await joinVoiceChannel({
                channelId: '...',
                guildId: g.id,
                adapterCreator: g.voiceAdapterCreator,
            });

            const connection = getVoiceConnection(g.id);
            let player = null;

            connection.on(VoiceConnectionStatus.Ready, () => {
                player = createAudioPlayer(); // consider params
                const resource = createAudioResource("...icecast url here...");
                player.play(resource);
                connection.subscribe(player);
            });

            setTimeout(() => {
                player?.stop();
                connection.destroy();
            }, 60000);
```

**Comment by thenfour** [comment]
with latest updates this is pretty much closed. setting up a stream source is probably a totally different project, and a new issue can be opened for it.
